### PR TITLE
fix: prevent double building mexes

### LINKED ISSUE #5221: Mexes can be double and even triple built
### Description

There is currently a bug where more than 1 mex can be placed on a single spot. The second mex does not produce metal but still costs energy (or in the case of legion, produces it)

### Expected Behaviour

It should be impossible to place more than 1 mex on a spot

### Actual Behaviour

More than 1 mex can be placed on a spot. The second mex costs (or produces) energy despite not producing metal.

### Reproduction steps

Place 2 mexes on one spot

### Other

_No response_

### PR DESCRIPTION
**Pull request by hihoman23**
### Work done
Prevents one ally team from making two mexes on the same metal spot.

- fixes #5221

### CODE REVIEW

**Comment by mr-maxo-PDG** [comment]
Awesome :O :O :O

File: luarules/gadgets/cmd_mex_denier.lua [hunk 1]
```diff
@@ -62,5 +71,39 @@ function gadget:AllowCommand(_, _, _, cmdID, cmdParams)
...
+	if not isMex[unitDefID] then
+		return true
+	end
+
+	local closestSpot = math.getClosestPosition(x, z, metalSpotsList)
+	if not closestSpot then
+		return false
+	end
+
+	local units = spGetUnitsInCylinder(closestSpot.x, closestSpot.z, Game_extractorRadius)
```
Comment (saurtron) [inline luarules/gadgets/cmd_mex_denier.lua]: Since starting on this line it's almost the same code as above, it'd be good to have a method with the common code instead of duplicating it. You can pass teamID and closestSpot I think that's all you need.

File: luarules/gadgets/cmd_mex_denier.lua [hunk 2]
```diff
@@ -62,5 +71,39 @@ function gadget:AllowCommand(_, _, _, cmdID, cmdParams)
...
+				return false
+			end
+		end
+	end
+
+	return true
+end
+
+-- function gadget:AllowUnitCreation(unitDefID, builderID, teamID, x, y, z, facing)
+function gadget:AllowUnitCreation(unitDefID, _, teamID, x, _, z)
```
Comment (saurtron) [inline luarules/gadgets/cmd_mex_denier.lua:91]: Looking for AllowUnitCreation engine, it seems to actually use two return values `{allow, drop}`, while current BAR only uses one.

Doesn't seem to make a big difference, I think the builder will stay in front of the mex for a sec before proceeding, instead of skip faster when drop is used.

Not a blocker and better not to tackle in this same PR (to not complicate it), but smth to keep in mind for the future.

**Review by saurtron — CHANGES_REQUESTED** [review]

File: luarules/gadgets/cmd_mex_denier.lua [hunk 3]
```diff
@@ -47,6 +47,19 @@ function gadget:Initialize()
 	metalSpotsList = GG["resource_spot_finder"].metalSpotsList
 end
 
+local function mexExists(spot, teamID, cmdX, cmdZ)
```
Comment (saurtron) [inline luarules/gadgets/cmd_mex_denier.lua]: should be `allyTeamID` here.

File: luarules/gadgets/cmd_mex_denier.lua [hunk 4]
```diff
@@ -94,16 +97,6 @@ function gadget:AllowUnitCreation(unitDefID, _, teamID, x, _, z)
...
-			local ux, _, uz = spGetUnitPosition(unit)
-			if not(ux == x and uz == z) and spGetUnitAllyTeam(unit) == spGetTeamAllyTeamID(teamID) then -- exclude upgrading mexes
-				return false
-			end
-		end
-	end
-
-	return true
+	
+	return not mexExists(closestSpot, teamID, x, z)
```
Comment (saurtron) [inline luarules/gadgets/cmd_mex_denier.lua]: should pass allyTeamID instead of teamID.

**Comment by WatchTheFort** [comment]
Isn't the proper solution to this to decrease mex spot radius so that only a single mex can fit in it?

**Comment by hihoman23** [comment]
I don't know, but this would take a lot of time and for the time this PR would fix the exploit mentioned in the issue.

**Comment by WybrenKoelmans** [comment]
throwing an idea out there: should the mexes divide the metal between them equally? It feels more intuitive to me than for one to work and the other does nothing. It also opens interesting co-op consequences.

**Comment by WatchTheFort** [comment]
@saurtron Can you please give this another review? It says there is one change requested, but all conversations are resolved, so looks like a Github bug.

**Comment by sprunk** [comment]
> @WatchTheFort It says there is one change requested, but all conversations are resolved, so looks like a Github bug.

It's because the negative review lingers if you re-request a review. It doesn't get cancelled, but its icon gets hidden by the yellow dot. If you temporarily cancel the request it shows the real status:
image

> @WybrenKoelmans should the mexes divide the metal between them equally?

Engine won't do this because it's a game design question[^1] so belongs to Lua, but BAR had a Lua mex implementation and threw it away recently in favour of the native engine behaviour. Somebody would have to revisit the tradeoffs.

[^1]: do you share with enemies? With ceasefired? What if one mex is stunned, does another take over its share temporarily? What if one mex has depth 1 and the other 2, do they produce 1 each or does the small/big produce 0.5/1.5 respectively? What if engine implements the planned non-metal resources from mexes, do you try to equalize sum, equalize each? Etc etc, answering all those is Lua's business.

File: luarules/gadgets/cmd_mex_denier.lua [hunk 5]
```diff
@@ -13,12 +13,21 @@ function gadget:GetInfo()
...
+local spGetUnitDefID = Spring.GetUnitDefID
+local spGetUnitAllyTeam = Spring.GetUnitAllyTeam
+local spGetPlayerInfo = Spring.GetPlayerInfo
+local spGetTeamAllyTeamID = Spring.GetTeamAllyTeamID
+local spGetUnitPosition = Spring.GetUnitPosition
+local spGetUnitsInCylinder = Spring.GetUnitsInCylinder
+
+local CMD_INSERT = CMD.INSERT
+
+local Game_extractorRadius = Game.extractorRadius
```
Comment (saurtron) [inline luarules/gadgets/cmd_mex_denier.lua]: Underscore is fine when original variable is all caps, like CMD_INSERT, but this should use smth like `gExtractorRadius` maybe (in the same style as `spGetUnitDefID = Spring.GetUnitDefID`)

**Review by saurtron — DISMISSED** [review]
Minor style remark, but imo should be fixed, otherwise looks fine.

Will approve as soon as that's fixed.

Also tested and seems to work fine.

**Review by thehobojoe — APPROVED** [review]
PAT
