### PR TITLE
Fix issue 3475 (units lose queue when multi-selection includes a transport giving a load/unload command)

### LINKED ISSUE #3475: T2con+transport selected, make a pickup circle = removes T2con orders
### Description

Not sure if this is related to the persistent orders in trans thingy but you cant have T2con selected at the same time as a transport when you pickup the T2con, this removes persistent orders immediately and as you unload T2con the orders for T2mexing is gone.

You can select transport individually and do pickup circle, question is if this is a bug or intended behaviour, what would be best is T2con not caring what 'J' is and keep doing its thing.

### Expected Behaviour

Select both T2con+Transport and load with J+circle.

### Actual Behaviour

T2con forgets orders as you release leftclick button after making circle.

### Reproduction steps

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by Brian-Catcow-B**
Closes #3475

### Work done

Have the AllowCommand gadget call-in return false if the selected unit isn't a transport for the commands CMD_LOAD_UNITS and CMD_UNLOAD_UNITS

#### Test steps
- [ ] Start a game
- [ ] `/cheat` then `/give armatlas` then `/give armack` then `/give corkorg`
- [ ] queue some things with the t2 con
- [ ] select both the t2 con and the t1 air transport
- [ ] right click the t2 con to load it
- [ ] unload it and see that the queue is still there (this is what the fix does - before the queue of the t2 con would go away)
- [ ] repeat with the juggernaut (but when right clicking to load you click to load the t2 con with the transport and jugg selected and before this fix the jugg would lose its queue)

#### Additional Notes

It is debatable as to whether or not this change should have gone into the file that it did, but in my opinion it makes a lot of sense to go there. The issue was caused by false positives being returned from gadget:AllowCommand for the commands CMD_LOAD_UNITS and CMD_UNLOAD_UNITS, which is exactly what the modified gadget file deals with, and that is the only place that handles those commands in gadget:AllowCommand (aside from some that handle all commands but don't really handle those two specifically in actuality). Plus, we shouldn't ever return true for AllowCommand if the unit isn't a transport in this context, soooooo it fixes the problem and that's why I went with it. No new file, 3 line fix that could be one line, big win.

### CODE REVIEW

**Comment by sprunk** [comment]
Is it consistent with other orders that a unit can't fulfil? Consider a bunch of scenarios where unit A can perform command C but unit B cannot:
1. A = transport, B = con, C = Load (directly addressed by this PR)
2. A = combat unit, B = con, C = Attack
2. A = con, B = combat unit, C = Reclaim or Repair
3. A = ground unit, B = air unit or building or juggernaut, C = load onto transport
4. A = factory, B = any non-factory, C = stop production
5. A = bertha, B = pawn, C = area attack

etc etc., do they behave consistently when both A and B are selected and command C is given?

**Comment by Brian-Catcow-B** [comment]
I haven't tested all of those yet. I did test some though. Things I tested:

1. Capture with a unit that can't capture also selected
2. Reclaim with a minelayer also selected

Both behaved effectively normally, but I did notice for capture that the commander still walks in range to capture the target unit even if the target gets killed. That would be a separate issue though. 

I could make a gadget that does AllowCommand with all commands registered (using CMD.ANY), then making sure to return true/false properly based on if the selected unit should be able to handle that command, but there are a few reasons I think that isn't a great idea. For one, I'm probably not familiar enough with the inner workings of each command and each field (like `isTransport`) to be able to implement this exactly properly. Second, it's nice to be able to regex the Lua codebase for "RegisterAllowCommand(*UNLOAD_UNITS)" or whatever command you're looking for an AllowCommand on to be able to see an implementation, which could be fixed by calling RegisterAllowCommand on all commands, but in the case of additional commands being registered, it would be harder to print a proper warning of that command not being handled by the gadget. Third, the case in this PR was a false positive that was very easily patched; I didn't look into the way AllowCommand is handled extensively, but I'm guessing it defaults to false if no AllowCommand exists for a specific command, and otherwise it does Boolean and to combine all the results of the calls to see if it should allow it; if this is the case, then basic checks to make sure the unit is even in the class of units that can do the action should always be done when a specific command is being handled as such, so I'm guessing there aren't any other bugs like this in the codebase. 

That said, I could look into making a gadget to ensure all this if you'd like.

**Comment by sprunk** [comment]
Generally the issue is for UI design to decide. The other questions are mostly to help them make a decision.

File: luarules/gadgets/unit_transportable_nanos.lua [hunk 1]
```diff
@@ -48,6 +48,9 @@ function gadget:Initialize()
 end
 
 function gadget:AllowCommand(unitID, unitDefID, teamID, cmdID, cmdParams, cmdOptions, cmdTag, playerID, fromSynced, fromLua)
+	if not UnitDefs[unitDefID].isTransport then
+		return false
```
Comment (efrec) [inline luarules/gadgets/unit_transportable_nanos.lua:52]:
```suggestion
		return true
```

and then LGTM (this was being a little cheeky so sorry)

Comment (Brian-Catcow-B) [reply luarules/gadgets/unit_transportable_nanos.lua:52]: if it's not a transport we should not allow the command (of loading/unloading units). Then continue with the other logic regarding whether or not the target (nano in this case) is transportable. What this fixes is the problem caused by all the applicable AllowCommand functions returning true and never considering whether or not the selected unit is a transport or not. This only ends up being applicable when multiple units are selected

Comment (Brian-Catcow-B) [reply luarules/gadgets/unit_transportable_nanos.lua:52]: The short version is:

No your change isn't correct. We don't allow non-transports to do load/unload commands is what my code is saying.

Comment (efrec) [reply luarules/gadgets/unit_transportable_nanos.lua:52]: Our pattern elsewhere throughout the game code is to check if a unit is in a category, process the command if so, else return true. This would follow the convention established elsewhere in code.

Another way of writing your approach might be structured like this:

```lua
if isTransport[id] then
   return isCommandAllowed(id)
end
return false
```

But you see the opposite patterning (`false` => `true`) in other files, e.g. `unit_air_plants` and `unit_builder_priority`.

I might agree that it's not intuitive. There are good and bad reasons for why we do it this way. But it is the common pattern.

Comment (efrec) [reply luarules/gadgets/unit_transportable_nanos.lua:52]: I should have read your PR description and responded to that instead though so that's my bad.

**Comment by efrec** [comment]
This is caused by the engine allowing the game's Lua code to control custom transport behaviors, so it does not check these in [AllowedCommand](https://github.com/beyond-all-reason/RecoilEngine/blob/defc0b1590101e85140cd72f8d17a6d4888070cf/rts/Sim/Units/CommandAI/CommandAI.cpp#L635-L813). That seems correct imo.

Now, in *rules* terms, you can issue bad commands to units. There's no real provision against that. The unit attempts to execute the  bad command, fails, and becomes idle. That's proper procedure for a gadget.

But in UI/UX terms, we would not want that. This change can be moved to a widget that strips unwanted commands when the player issues a load/unload command to a selection of several units.

File: luarules/gadgets/unit_transportable_nanos.lua (hunk 1 above)
Comment (efrec) [reply luarules/gadgets/unit_transportable_nanos.lua:52]: K, did so. You can dismiss this. I did not have a very good excuse for being a gremlin in a review. But the point is that we wouldn't make this change. See notes below.
