### PR TITLE
Unlink **Resource Sharing Tax** and **Disable Unit Sharing**

### LINKED ISSUE #4415: Unlink **Resource Sharing Tax** and **Disable Unit Sharing**
## Context  
The current implementation tightly links the **Resource Sharing Tax** setting to unit-sharing restrictions. While closing loopholes in the tax system is understandable, this approach limits usability. For unit sharing to be useful in most lobbies, it needs more flexibility, as discussed in [this issue](https://github.com/beyond-all-reason/Beyond-All-Reason/issues/4416).  

Allowing the community to experiment with the **Resource Sharing Tax** setting independently would be beneficial.

### Expected Behavior  
When setting a non-zero value for **Resource Sharing Tax**:  
- **Disable Unit Sharing** and **Disable Assist Ally Construction** should remain unchanged.  
- These settings should not be automatically enabled or locked.

### Actual Behavior  
When setting a non-zero value for **Resource Sharing Tax**:  
- **Disable Unit Sharing** and **Disable Assist Ally Construction** are forcibly enabled.  
- These settings become locked and cannot be adjusted.

### Steps to Reproduce  
1. Set a non-zero value for **Resource Sharing Tax** in the lobby settings.  
2. Observe that **Disable Unit Sharing** and **Disable Assist Ally Construction** are automatically enabled and locked.  

### Additional Information  
_No additional details at this time._

### PR DESCRIPTION
**Pull request by keithharvey**
closes #4415

### Description
Decouples resource sharing tax from unit sharing restrictions. Previously, setting a non-zero resource sharing tax would automatically enable and lock both "Disable Unit Sharing" and "Disable Assist Ally Construction" settings. This change removes that forced coupling, allowing these settings to be configured independently.

#### Changes
- Removed lock/unlock behavior from resource sharing tax
- Removed forced state UI indicators
- Settings remain functionally independent

#### Test steps
1. Open game settings under Main tab
2. Set Resource Sharing Tax to a non-zero value (e.g. 0.4)
3. Verify that both settings remain independently configurable:
   - Disable Unit Sharing
   - Disable Assist Ally Construction

#### Before
image

#### After
image

### Testers
This PR is contained in [this](https://github.com/beyond-all-reason/Beyond-All-Reason/pull/4447) branch and I would probably just test that once and then we can merge both PRs simultaneously.

### CODE REVIEW

File: modoptions.lua [hunk 1]
```diff
@@ -244,17 +244,14 @@ local options = {
 		key		= "tax_resource_sharing_amount",
 		name	= "Resource Sharing Tax",
 		desc	=	"Taxes resource sharing".."\255\128\128\128".." and overflow (engine TODO:)\n"..
-					"Set to [0] to turn off. Recommened: [0.4]. (Ranges: 0 - 0.99)\n"..
-					"*Disables: Reclaiming of Allied Units, [Unit Sharing] and [Assisting Ally Construction] to prevent loopholes",
+					"Set to [0] to turn off. Recommened: [0.4]. (Ranges: 0 - 0.99)",
```
Comment (sprunk) [inline modoptions.lua:247]: If you're touching the line then may as well:
```suggestion
					"Set to [0] to turn off. Recommended: [0.4]. (Ranges: 0 - 0.99)",
```

**Comment by WatchTheFort** [comment]
> @WatchTheFort would it be possible to review #4447 instead? That is a superset of this that and I think would make more sense to release both together.

If #4447 depends on this PR, then this PR should be reviewed first.

File: luarules/gadgets/game_disable_assist_ally.lua [hunk 2]
```diff
@@ -16,9 +16,10 @@ end
...
 end
-if	not (Spring.GetModOptions().disable_assist_ally_construction
-	-- tax force enables this
-	or (Spring.GetModOptions().tax_resource_sharing_amount or 0) ~= 0) then
+
+local disable_assist = Spring.GetModOptions().disable_assist_ally_construction
+
+if not disable_assist then
 	return false
 end
```
Comment (WatchTheFort) [inline luarules/gadgets/game_disable_assist_ally.lua:24]: This is a triple negative, very confusing

File: luarules/gadgets/game_disable_assist_ally.lua [hunk 3]
```diff
@@ -17,10 +17,10 @@ if not gadgetHandler:IsSyncedCode() then
...
 
-local disable_assist = Spring.GetModOptions().disable_assist_ally_construction
+local disableAssist = Spring.GetModOptions().disable_assist_ally_construction
```
Comment (WatchTheFort) [inline luarules/gadgets/game_disable_assist_ally.lua:20]:
```suggestion
local allowAssist = not Spring.GetModOptions().disable_assist_ally_construction
```

File: luarules/gadgets/game_disable_assist_ally.lua [hunk 4]
```diff
@@ -17,10 +17,10 @@ if not gadgetHandler:IsSyncedCode() then
...
 
-if not disable_assist then
-	return false
+if disableAssist then
+	return true
 end
```
Comment (WatchTheFort) [inline luarules/gadgets/game_disable_assist_ally.lua:24]: I don't think this this does what you intend. If the modoption to disable assisting is set, it will return early and not run any of the other code in the file, which will not disable assisting.
```suggestion
if allowAssist then
	return false
end
```

Comment (keithharvey) [reply luarules/gadgets/game_disable_assist_ally.lua:24]: Ah you're right I should've tested that thanks.

**Review by WatchTheFort — APPROVED** [review]
